import Head from 'next/head'
import DoCard from '../src/Componets/DoCard'
import EditCard from '../src/Componets/EditCard'
import { useContext, useEffect } from 'react';
import { NavContext, SectionsContext } from '../src/Componets/Context';

export default function Home() {

  const [sections] = useContext(SectionsContext)
  const [page, setPage] = useContext(NavContext)


  useEffect(() => {
    if (page === "Home") return;
    setPage("Home")
  }, [])


  return (
    <div>
      <Head>
        <title>Royal Priesthood Dashboard | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        sections?.map((section) => (
          <EditCard document={section} collection="Home" key={section} >
            {
              section === "What we do" ? (
                <>
                  <DoCard title="Worship/Praise" />
                  <DoCard title="Counseling" />
                  <DoCard title="Holy Communion" />
                  <DoCard title="Baptism" />
                </>
              ) : null
            }
          </EditCard>
        ))
      }
    </div>
  )
}
