import Head from 'next/head'
import VideoCard from '../src/Componets/VideoCard'
import AudioCard from '../src/Componets/AudioCard'
import EditCard from '../src/Componets/EditCard'
import { useContext, useEffect } from 'react';
import { NavContext, SectionsContext } from '../src/Componets/Context';

export default function Ministry() {

    const [sections] = useContext(SectionsContext)
    const [page, setPage] = useContext(NavContext)


    useEffect(() => {
        if (page === "Ministry") return;
        setPage("Ministry")
    }, [])


    return (
        <div>
            <Head>
                <title>Royal Priesthood Dashboard | Ministry</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                sections?.map((section) => (
                    <EditCard document={section} collection="Ministry" key={section} />
                ))
            }
        </div>
    )
}
